ci: Introduce Auto-Releases
camunda/infra-logrotate pull request #22
Opened 2024-10-29 09:47 UTC by kellervater

Straight forward semVer release introduction. Did NOT introduce a conventional commits enforcer since it's a fork of a repo which doesn't use this standard.

2024-10-29 16:49 UTC, maxdanilov reviewed
would it mean the version of the repo will start deviating from the logrotate version?

2024-10-30 07:49 UTC, kellervater commented
Yes, like discussed:
* We could either close this one and leave it as is, because there are no high frequency releases
* Or we approve this one and it deviates. But I'm not aware of any dependents which this may have an effect on
* OR... we create some kind of sophisticated update scripts/ci which reflect the the version of logrotate when being changed. This would be achievable through a so called `Release-As` commit on the release-please PR. But that introduces a considerable amount of complexity and edge cases.

2024-10-30 10:26 UTC, maxdanilov commented
What I mean is, if we deviate from the logrotate version, that's fine, but then we need to pick another version aside from 3.21.0 as a starting version here. The problem if that we don't, for the first releases it would create a false impression that we're still following the logrotate's version.

2024-10-30 10:27 UTC, maxdanilov requested changes
See my comment above for the versioning.

2024-10-30 11:01 UTC, kellervater commented
Then I'd say we bump to the next major version to clearly differentiate here.
It's possible like described in here: https://github.com/camunda/infra-actions-runner/pull/23#issuecomment-2446186173

2024-10-30 13:35 UTC, maxdanilov commented on .github/config/.release-please-manifest.json
> +  ".": "3.21.0"
is this line still needed considering we'll change a different version here (like 4.0.0)

2024-10-30 13:38 UTC, kellervater commented on .github/config/.release-please-manifest.json
> +  ".": "3.21.0"
yes, because otherwise the Changelog would be bloated with basically any change ever.
it represents the current latest release. 
after the merge of this PR here
a new release pr will be created. Then we make the empty release-as commit and it'll update to the next major version.

2024-10-30 13:43 UTC, maxdanilov approved these changes

2024-10-30 13:46 UTC, merged

2024-10-30 13:51 UTC, kellervater commented
For completeness:
We will bump to `4.0.0` with the next release:
* https://github.com/camunda/infra-logrotate/pull/23